### ISSUE TITLE
Proper query-params handling

### ISSUE THREAD

**Issue by kirillsalykin** [schmee/java-http-clj#3]
Currently it is possible to pass only `uri` as param, would be nice to be able to pass the query-params as well.

```
{:method :get
  :uri    "http://example.com"
  :query-params {:q "test", "other" "value"}}
```

Query params name(s) and value(s) should be encoded.

Thanks.

**Comment by schmee** [comment]
Hi @kirillsalykin,

java-http-clj aims to be a direct and minimal wrapper around java.net.http, and since query param handling is not part of the [HttpClient](https://docs.oracle.com/en/java/javase/15/docs/api/java.net.http/java/net/http/HttpClient.html) API, java-http-clj won't have that functionality either. You can accomplish what you need by using for example [lambdaisland/uri](https://github.com/lambdaisland/uri) `map->query-string` (or [ring-codec](https://github.com/ring-clojure/ring-codec) `form-encode`):

```clojure
(->> (uri/map->query-string {:q "test" "other" "value"})
     (assoc (uri/uri "http://example.com") :query)
     str)
; => "http://example.com?q=test&other=value"
```
and then pass that as `uri` to the java-http-clj 👍
